---
# ServiceAccount for Jaeger
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger
  namespace: kagent
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/version: "2.7.0"
    app.kubernetes.io/component: tracing
---
# Service for Jaeger Collector (OTLP endpoints)
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: kagent
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/version: "2.7.0"
    app.kubernetes.io/component: collector
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
---
# Service for Jaeger Query UI
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: kagent
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/version: "2.7.0"
    app.kubernetes.io/component: query
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 16686
      protocol: TCP
      targetPort: 16686
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
---
# Deployment for Jaeger All-in-One
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: kagent
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/version: "2.7.0"
    app.kubernetes.io/component: all-in-one
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/instance: jaeger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/instance: jaeger
        app.kubernetes.io/version: "2.7.0"
        app.kubernetes.io/component: all-in-one
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: jaeger
      containers:
        - name: jaeger
          image: jaegertracing/jaeger:2.7.0
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: SPAN_STORAGE_TYPE
              value: "memory"
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: http-query
              containerPort: 16686
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      terminationGracePeriodSeconds: 30
